// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/.well-known/openid-configuration": {
            "get": {
                "description": "OIDC认证相关接口",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC认证"
                ],
                "summary": "获取配置",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/auth/dingtalk_login": {
            "post": {
                "description": "用户认证相关接口",
                "tags": [
                    "用户认证"
                ],
                "summary": "钉钉扫码认证",
                "parameters": [
                    {
                        "description": "授权请求参数",
                        "name": "authorize",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.DingTalkLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"token\": \"用户令牌\", \"redirect_uri\": redirect_uri}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/feishu_login": {
            "post": {
                "description": "用户认证相关接口",
                "tags": [
                    "用户认证"
                ],
                "summary": "飞书扫码认证",
                "parameters": [
                    {
                        "description": "授权请求参数",
                        "name": "authorize",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.FeishuLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"token\": \"用户令牌\", \"redirect_uri\": redirect_uri}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "用户认证相关接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "账号密码认证",
                "parameters": [
                    {
                        "description": "用户名密码",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"token\": \"用户令牌\", \"redirect_uri\": redirect_uri}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "description": "用户认证相关接口",
                "tags": [
                    "用户认证"
                ],
                "summary": "注销",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/ww_login": {
            "post": {
                "description": "用户认证相关接口",
                "tags": [
                    "用户认证"
                ],
                "summary": "企业微信扫码认证",
                "parameters": [
                    {
                        "description": "授权请求参数",
                        "name": "authorize",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.WeChatLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"token\": \"用户令牌\", \"redirect_uri\": redirect_uri}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/audit/login": {
            "get": {
                "description": "审计相关接口",
                "tags": [
                    "登录日志管理"
                ],
                "summary": "获取系统登录记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页大小",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": []}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/audit/sms": {
            "get": {
                "description": "审计相关接口",
                "tags": [
                    "短信发送记录管理"
                ],
                "summary": "获取短信发送记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页大小",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "电话号码",
                        "name": "receiver",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": []}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/audit/sms/receipt": {
            "get": {
                "description": "审计相关接口",
                "tags": [
                    "登录日志管理"
                ],
                "summary": "获取短信回执（阿里云）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "短信记录ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group": {
            "put": {
                "description": "组相关接口",
                "tags": [
                    "组管理"
                ],
                "summary": "更新组信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "组信息",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.GroupUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"更新成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "组相关接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组管理"
                ],
                "summary": "创建组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "组信息",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.GroupCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"创建成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/permissions": {
            "put": {
                "description": "组相关接口",
                "tags": [
                    "组管理"
                ],
                "summary": "更新组权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "权限名称",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.GroupUpdatePermission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"更新成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/users": {
            "put": {
                "description": "组相关接口",
                "tags": [
                    "组管理"
                ],
                "summary": "更新组用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.GroupUpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"更新成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/group/{id}": {
            "delete": {
                "description": "组相关接口",
                "tags": [
                    "组管理"
                ],
                "summary": "删除组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "组ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"删除成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/groups": {
            "get": {
                "description": "组相关接口",
                "tags": [
                    "组管理"
                ],
                "summary": "获取组列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页大小",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "组名称",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": []}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/menu/list": {
            "get": {
                "description": "组相关接口",
                "tags": [
                    "组管理"
                ],
                "summary": "获取所菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": []}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/menus": {
            "get": {
                "description": "菜单关接口",
                "tags": [
                    "菜单管理"
                ],
                "summary": "获取菜单列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页大小",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": []}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/oauth/token": {
            "post": {
                "description": "OAuth2.0认证相关接口",
                "tags": [
                    "OAuth2.0认证"
                ],
                "summary": "客户端认证",
                "parameters": [
                    {
                        "description": "授权请求参数",
                        "name": "authorize",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.Token"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ResponseToken"
                        }
                    }
                }
            }
        },
        "/api/v1/oauth/userinfo": {
            "get": {
                "description": "OAuth2.0认证相关接口",
                "tags": [
                    "OAuth2.0认证"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ResponseUserinfo"
                        }
                    }
                }
            }
        },
        "/api/v1/path/list": {
            "get": {
                "description": "组相关接口",
                "tags": [
                    "组管理"
                ],
                "summary": "获取所有接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": []}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/paths": {
            "get": {
                "description": "接口相关接口",
                "tags": [
                    "接口管理"
                ],
                "summary": "获取接口列表（表格展示）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页大小",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "菜单名称",
                        "name": "menu_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": []}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/reset_password": {
            "post": {
                "description": "个人信息管理相关接口",
                "tags": [
                    "个人信息管理"
                ],
                "summary": "密码更新",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dao.UserPasswordUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"更新成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/site": {
            "put": {
                "description": "站点关接口",
                "tags": [
                    "站点管理"
                ],
                "summary": "更新站点信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "分组信息",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dao.UpdateSite"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"更新成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "站点关接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点管理"
                ],
                "summary": "创建站点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "分组信息",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SiteCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"创建成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/site/group": {
            "put": {
                "description": "站点关接口",
                "tags": [
                    "站点管理"
                ],
                "summary": "更新分组信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "分组信息",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SiteGroupUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"更新成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "站点关接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点管理"
                ],
                "summary": "创建分组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "分组信息",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SiteGroupCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"创建成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/site/group/{id}": {
            "delete": {
                "description": "站点关接口",
                "tags": [
                    "站点管理"
                ],
                "summary": "删除站点分组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分组ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"删除成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/site/guide": {
            "get": {
                "description": "站点关接口",
                "tags": [
                    "站点管理"
                ],
                "summary": "获取站点列表（导航）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": []}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/site/logoUpload": {
            "post": {
                "description": "站点关接口",
                "tags": [
                    "站点管理"
                ],
                "summary": "站点图片上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "头像",
                        "name": "logo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"path\": logoPath}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/site/tags": {
            "put": {
                "description": "站点关接口",
                "tags": [
                    "站点管理"
                ],
                "summary": "更新站点标签",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SiteTagUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"更新成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/site/users": {
            "put": {
                "description": "站点关接口",
                "tags": [
                    "站点管理"
                ],
                "summary": "更新站点用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SiteUserUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"更新成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/site/{id}": {
            "delete": {
                "description": "站点关接口",
                "tags": [
                    "站点管理"
                ],
                "summary": "删除站点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分组ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"删除成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/sites": {
            "get": {
                "description": "站点关接口",
                "tags": [
                    "站点管理"
                ],
                "summary": "获取站点列表（表格）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页大小",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "站点名称",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": []}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/sms/reset_password": {
            "post": {
                "description": "个人信息管理相关接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "个人信息管理"
                ],
                "summary": "获取验证码",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.RestPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"校验码已发送...\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/sso/cas/authorize": {
            "post": {
                "description": "CAS3.0认证相关接口",
                "tags": [
                    "CAS3.0认证"
                ],
                "summary": "客户端授权",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "授权请求参数",
                        "name": "authorize",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CASAuthorize"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": 授权成功, \"redirect_uri\": redirect_uri}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/sso/cookie/auth": {
            "get": {
                "description": "Cookie认证相关接口",
                "tags": [
                    "Cookie认证"
                ],
                "summary": "Cookie认证",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/sso/oauth/authorize": {
            "post": {
                "description": "OAuth2.0认证相关接口",
                "tags": [
                    "OAuth2.0认证"
                ],
                "summary": "客户端授权",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "授权请求参数",
                        "name": "authorize",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.OAuthAuthorize"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": 授权成功, \"redirect_uri\": redirect_uri}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/sso/oidc/jwks": {
            "get": {
                "description": "OIDC认证相关接口",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC认证"
                ],
                "summary": "获取jwks",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/sso/saml/authorize": {
            "post": {
                "description": "SAML2认证相关接口",
                "tags": [
                    "SAML2认证"
                ],
                "summary": "SP授权",
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/sso/saml/metadata": {
            "get": {
                "description": "SAML2认证相关接口",
                "produces": [
                    "text/xml"
                ],
                "tags": [
                    "SAML2认证"
                ],
                "summary": "获取元数据",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "SAML2认证相关接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SAML2认证"
                ],
                "summary": "SP Metadata解析",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "授权请求参数",
                        "name": "url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.ParseSPMetadata"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "put": {
                "description": "用户相关接口",
                "tags": [
                    "用户管理"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dao.UserUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"更新成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "用户相关接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dao.UserCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"创建成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/avatarUpload": {
            "post": {
                "description": "个人信息管理相关接口",
                "tags": [
                    "个人信息管理"
                ],
                "summary": "头像上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "头像",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/info": {
            "get": {
                "description": "用户认证相关接口",
                "tags": [
                    "用户认证"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": {}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/list": {
            "get": {
                "description": "用户相关接口",
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户列表（下拉框）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": []}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/mfa_auth": {
            "post": {
                "description": "用户认证相关接口",
                "tags": [
                    "用户认证"
                ],
                "summary": "MFA认证",
                "parameters": [
                    {
                        "description": "MFA认证信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.MFAValidate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"token\": \"用户令牌\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/mfa_qrcode": {
            "get": {
                "description": "用户认证相关接口",
                "tags": [
                    "用户认证"
                ],
                "summary": "获取MFA二维码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户认证通过后的Token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"qrcode\": \"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/reset_mfa/{id}": {
            "put": {
                "description": "用户相关接口",
                "tags": [
                    "用户管理"
                ],
                "summary": "MFA重置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"重置成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/reset_password": {
            "put": {
                "description": "用户相关接口",
                "tags": [
                    "用户管理"
                ],
                "summary": "密码更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dao.UserPasswordUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"更新成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/sync/ad": {
            "post": {
                "description": "用户相关接口",
                "tags": [
                    "用户管理"
                ],
                "summary": "LDAP用户同步",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"同步成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}": {
            "delete": {
                "description": "用户相关接口",
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"msg\": \"删除成功\", \"data\": nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "description": "用户相关接口",
                "tags": [
                    "用户管理"
                ],
                "summary": "获取查询的用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页大小",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户姓名",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0, \"data\": []}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/p3/serviceValidate": {
            "get": {
                "description": "CAS3.0认证相关接口",
                "produces": [
                    "text/xml"
                ],
                "tags": [
                    "CAS3.0认证"
                ],
                "summary": "票据校验",
                "parameters": [
                    {
                        "description": "授权请求参数",
                        "name": "authorize",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CASServiceValidate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "dao.UpdateSite": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "all_open": {
                    "description": "指针类型，可以确保使用Updates方法更新时，如果值为false时也能更新成功",
                    "type": "boolean"
                },
                "callback_url": {
                    "type": "string"
                },
                "certificate": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "entity_id": {
                    "description": "指针类型，可以确保使用Updates方法更新时，如果值为空时也能更新成功",
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sso": {
                    "description": "指针类型，可以确保使用Updates方法更新时，如果值为false时也能更新成功",
                    "type": "boolean"
                },
                "sso_type": {
                    "type": "integer"
                }
            }
        },
        "dao.UserCreate": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "phone_number",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "user_from": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dao.UserPasswordUpdate": {
            "type": "object",
            "required": [
                "id",
                "password",
                "re_password"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "re_password": {
                    "type": "string"
                }
            }
        },
        "dao.UserUpdate": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "phone_number": {
                    "type": "string"
                },
                "ww_id": {
                    "type": "string"
                }
            }
        },
        "service.CASAuthorize": {
            "type": "object",
            "required": [
                "service"
            ],
            "properties": {
                "service": {
                    "type": "string"
                }
            }
        },
        "service.CASServiceValidate": {
            "type": "object",
            "required": [
                "service",
                "ticket"
            ],
            "properties": {
                "service": {
                    "type": "string"
                },
                "ticket": {
                    "type": "string"
                }
            }
        },
        "service.DingTalkLogin": {
            "type": "object",
            "required": [
                "authCode"
            ],
            "properties": {
                "RelayState": {
                    "description": "SAML2客户端：客户端状态码",
                    "type": "string"
                },
                "SAMLRequest": {
                    "description": "SAML2客户端：SAMLRequest",
                    "type": "string"
                },
                "SigAlg": {
                    "description": "SAML2客户端：签名算法",
                    "type": "string"
                },
                "Signature": {
                    "description": "SAML2客户端：签名",
                    "type": "string"
                },
                "authCode": {
                    "type": "string"
                },
                "client_id": {
                    "description": "OAuth2.0客户端：客户端ID",
                    "type": "string"
                },
                "redirect_uri": {
                    "description": "OAuth2.0客户端：重定向URL",
                    "type": "string"
                },
                "response_type": {
                    "description": "OAuth2.0客户端：授权类型，固定值：code",
                    "type": "string"
                },
                "scope": {
                    "description": "OAuth2.0客户端：申请权限范围",
                    "type": "string"
                },
                "service": {
                    "description": "CAS3.0客户端：回调地址",
                    "type": "string"
                },
                "state": {
                    "description": "OAuth2.0客户端：客户端状态码",
                    "type": "string"
                }
            }
        },
        "service.FeishuLogin": {
            "type": "object",
            "required": [
                "byte",
                "code"
            ],
            "properties": {
                "RelayState": {
                    "description": "SAML2客户端：客户端状态码",
                    "type": "string"
                },
                "SAMLRequest": {
                    "description": "SAML2客户端：SAMLRequest",
                    "type": "string"
                },
                "SigAlg": {
                    "description": "SAML2客户端：签名算法",
                    "type": "string"
                },
                "Signature": {
                    "description": "SAML2客户端：签名",
                    "type": "string"
                },
                "byte": {
                    "description": "自定义参数",
                    "type": "string"
                },
                "client_id": {
                    "description": "OAuth2.0客户端：客户端ID",
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "redirect_uri": {
                    "description": "OAuth2.0客户端：重定向URL",
                    "type": "string"
                },
                "response_type": {
                    "description": "OAuth2.0客户端：授权类型，固定值：code",
                    "type": "string"
                },
                "scope": {
                    "description": "OAuth2.0客户端：申请权限范围",
                    "type": "string"
                },
                "service": {
                    "description": "CAS3.0客户端：回调地址",
                    "type": "string"
                },
                "state": {
                    "description": "OAuth2.0客户端：客户端状态码",
                    "type": "string"
                }
            }
        },
        "service.GroupCreate": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "is_role_group": {
                    "type": "boolean",
                    "default": false
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.GroupUpdate": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.GroupUpdatePermission": {
            "type": "object",
            "required": [
                "id",
                "menu_permissions",
                "path_permissions"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "menu_permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "path_permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "service.GroupUpdateUser": {
            "type": "object",
            "required": [
                "id",
                "users"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "service.MFAValidate": {
            "type": "object",
            "required": [
                "code",
                "token",
                "username"
            ],
            "properties": {
                "RelayState": {
                    "description": "SAML2客户端：客户端状态码",
                    "type": "string"
                },
                "SAMLRequest": {
                    "description": "SAML2客户端：SAMLRequest",
                    "type": "string"
                },
                "SigAlg": {
                    "description": "SAML2客户端：签名算法",
                    "type": "string"
                },
                "Signature": {
                    "description": "SAML2客户端：签名",
                    "type": "string"
                },
                "client_id": {
                    "description": "OAuth2.0客户端：客户端ID",
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "nginx_redirect_uri": {
                    "description": "Nginx代理客户端：回调地址",
                    "type": "string"
                },
                "redirect_uri": {
                    "description": "OAuth2.0客户端：重定向URL",
                    "type": "string"
                },
                "response_type": {
                    "description": "OAuth2.0客户端：授权类型，固定值：code",
                    "type": "string"
                },
                "scope": {
                    "description": "OAuth2.0客户端：申请权限范围",
                    "type": "string"
                },
                "service": {
                    "description": "CAS3.0客户端：回调地址",
                    "type": "string"
                },
                "state": {
                    "description": "OAuth2.0客户端：客户端状态码",
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.OAuthAuthorize": {
            "type": "object",
            "required": [
                "client_id",
                "response_type"
            ],
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "redirect_uri": {
                    "type": "string"
                },
                "response_type": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "service.ParseSPMetadata": {
            "type": "object",
            "required": [
                "sp_metadata_url"
            ],
            "properties": {
                "sp_metadata_url": {
                    "type": "string"
                }
            }
        },
        "service.ResponseToken": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "id_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "service.ResponseUserinfo": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "用户姓名",
                    "type": "string"
                },
                "phone_number": {
                    "description": "电话号码",
                    "type": "string"
                },
                "preferred_username": {
                    "description": "首选用户名",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "service.RestPassword": {
            "type": "object",
            "required": [
                "code",
                "password",
                "phone_number",
                "re_password",
                "username"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "re_password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.SiteCreate": {
            "type": "object",
            "required": [
                "address",
                "description",
                "name",
                "site_group_id",
                "sso"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "callback_url": {
                    "type": "string"
                },
                "certificate": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "domain_id": {
                    "type": "string"
                },
                "entity_id": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "idp_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "redirect_url": {
                    "type": "string"
                },
                "site_group_id": {
                    "type": "integer"
                },
                "sso": {
                    "type": "boolean"
                },
                "sso_type": {
                    "type": "integer"
                }
            }
        },
        "service.SiteGroupCreate": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "service.SiteGroupUpdate": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.SiteTagUpdate": {
            "type": "object",
            "required": [
                "id",
                "tags"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "service.SiteUserUpdate": {
            "type": "object",
            "required": [
                "id",
                "users"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "service.Token": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "grant_type": {
                    "type": "string"
                },
                "redirect_uri": {
                    "type": "string"
                }
            }
        },
        "service.UserLogin": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "RelayState": {
                    "description": "SAML2客户端：客户端状态码",
                    "type": "string"
                },
                "SAMLRequest": {
                    "description": "SAML2客户端：SAMLRequest",
                    "type": "string"
                },
                "SigAlg": {
                    "description": "SAML2客户端：签名算法",
                    "type": "string"
                },
                "Signature": {
                    "description": "SAML2客户端：签名",
                    "type": "string"
                },
                "client_id": {
                    "description": "OAuth2.0客户端：客户端ID",
                    "type": "string"
                },
                "nginx_redirect_uri": {
                    "description": "Nginx代理客户端：回调地址",
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "redirect_uri": {
                    "description": "OAuth2.0客户端：重定向URL",
                    "type": "string"
                },
                "response_type": {
                    "description": "OAuth2.0客户端：授权类型，固定值：code",
                    "type": "string"
                },
                "scope": {
                    "description": "OAuth2.0客户端：申请权限范围",
                    "type": "string"
                },
                "service": {
                    "description": "CAS3.0客户端：回调地址",
                    "type": "string"
                },
                "state": {
                    "description": "OAuth2.0客户端：客户端状态码",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.WeChatLogin": {
            "type": "object",
            "required": [
                "appid",
                "code"
            ],
            "properties": {
                "RelayState": {
                    "description": "SAML2客户端：客户端状态码",
                    "type": "string"
                },
                "SAMLRequest": {
                    "description": "SAML2客户端：SAMLRequest",
                    "type": "string"
                },
                "SigAlg": {
                    "description": "SAML2客户端：签名算法",
                    "type": "string"
                },
                "Signature": {
                    "description": "SAML2客户端：签名",
                    "type": "string"
                },
                "appid": {
                    "type": "string"
                },
                "client_id": {
                    "description": "OAuth2.0客户端：客户端ID",
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "redirect_uri": {
                    "description": "OAuth2.0客户端：重定向URL",
                    "type": "string"
                },
                "response_type": {
                    "description": "OAuth2.0客户端：授权类型，固定值：code",
                    "type": "string"
                },
                "scope": {
                    "description": "OAuth2.0客户端：申请权限范围",
                    "type": "string"
                },
                "service": {
                    "description": "CAS3.0客户端：回调地址",
                    "type": "string"
                },
                "state": {
                    "description": "OAuth2.0客户端：客户端状态码",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
